name: BattleBuilders
main: Zade\BuildMain
api: [3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12]
version: 5.0.7.1-Zade
author: Zadezter
website: http://github.com/Zadezter/BattleBuilders

commands:
    buildcreate:
        usage: /buildcreate <world>
        description: Create a new BattleBuilders arena!
permissions:
    battlebuilders.command.op:
        default: op
  
