name: BattleBuilders
main: Zade\BuildMain
api: [3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12]
version: 5.0.6-Zade
author: Zadezter
website: http://github.com/Zadezter/BattleBuilders
commands:
    buildcreate:
        usage: /buildcreate <world> to setup the arena!
        description: Create a BattleBuilders arena!
        aliases: ["bb","battlebuilders"]
permissions:
    battlebuilders.op:
        default: op
  